name: Google Agile Docs Screenshots
on:
  push:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      MOVE_TO_MOUSE_CURSOR: false
      DISABLE_HIGHLIGHTS: false
      DISABLE_SCREENSHOTS: false
      DISABLE_VIDEO: true
      MOUSE_VERTICAL_OFFSET: 74
    steps:
      - uses: actions/checkout@v1
      - name: Configure VM
        run: ./puppet/install.sh setup.pp
      - name: Run script
        uses: docker://mcasperson/webdriver
        env:
          JAVA_OPTS: >
            -DmoveCursorToElement=${MOVE_TO_MOUSE_CURSOR}
            -DdisableHighlights=${DISABLE_HIGHLIGHTS}
            -DdisableScreenshots=${DISABLE_SCREENSHOTS}
            -DmouseMoveVerticalOffset=${MOUSE_VERTICAL_OFFSET}
            -DdisableVideoRecording=${DISABLE_VIDEO}
            -DCucumberAlias-ExternalVideoDir=/github/workspace
            -DCucumberAlias-ExternalScreenshotDir=/github/workspace
        with:
          args: --plugin=progress /github/workspace/google.feature
      - name: Upload screenshots
        run: aws s3 sync "/home/runner/work/GoogleAgileDocs/GoogleAgileDocs" s3://i.octopus.com/guides/google --acl public-read --exclude "*" --include "*.png"