name: Google Agile Docs Screenshots
on:
#  push:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      WISTIA_USERNAME: ${{ secrets.WISTIA_USERNAME }}
      WISTIA_PASSWORD: ${{ secrets.WISTIA_PASSWORD }}
      MOVE_TO_MOUSE_CURSOR: false
      DISABLE_HIGHLIGHTS: false
      DISABLE_SCREENSHOTS: false
      DISABLE_VIDEO: true
      DISPLAY: ":99.0"
      MOUSE_VERTICAL_OFFSET: 74
      WISTIA_MEDIA_ID:
    steps:
      - uses: actions/checkout@v1
      - name: Configure VM
        run: ./puppet/install.sh setup.pp
      - name: Run Script
        run:
      - name: Upload screenshots
        run: aws s3 sync "/tmp/screenshots" s3://i.octopus.com/guides --acl public-read